frameworkVersion: ">=1.64.0 <2.0.0"
service: elasticsearch-queries
provider:
  name: aws
  runtime: python3.7
  memorySize: 1024
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:custom.deploymentBucket.${self:provider.stage}, self:custom.deploymentBucket.dev}
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  rolePermissionsBoundary: "arn:aws:iam::#{AWS::AccountId}:policy/oslokommune/oslokommune-boundary"
  iamManagedPolicies:
    - 'arn:aws:iam::#{AWS::AccountId}:policy/elasticsearch-queries-policy'
    - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    STAGE: ${self:provider.stage}
    VERSION: ${self:custom.version}
    ES_ENDPOINT: ***REMOVED***
    ES_REGION: eu-west-1
    AUTHORIZER_API: ${ssm:/dataplatform/shared/api-gateway-url}/simple-dataset-authorizer
    ENABLE_AUTH: true
    KEYCLOAK_SERVER: ${ssm:/dataplatform/shared/keycloak-server-url}
    KEYCLOAK_REALM: api-catalog
    CLIENT_ID: elasticsearch-queries
    CLIENT_SECRET: ${ssm:/dataplatform/apis/elasticsearch-queries/auth/client_secret~true}
package:
  exclude:
    - '**/*'
  include:
    - queries/*.py
    - aws/*.py


functions:
  event_stat: ${file(serverless/functions/event_stat.yaml)}

plugins:
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-es-logs

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  esLogs:
    endpoint: ${ssm:/dataplatform/shared/logs-elasticsearch-endpoint}
    index: dataplatform-services
    filterPattern: '{ $.function_name = "*" }'
  exportGitVariables: false
  deploymentBucket:
    prod: ok-origo-dataplatform-config-prod
    dev: ok-origo-dataplatform-config-dev
